### ISSUE TITLE
Support .NET Core 3.1 and EFCore 3.1

### ISSUE THREAD

**Issue by xcaptain** [casbin-net/EFCore-Adapter#12]
This project depends on .net 2.2, now we should upgrade to .net core 3.1

https://github.com/casbin-net/EFCore-Adapter/blob/d0049905cc417f4aa2638d3c60c0ef1dbad2eed0/EFCore-Adapter/EFCore-Adapter.csproj#L11-L12

**Comment by AaqibAhamed** [comment]
@xcaptain  This issue has been sorted.Find my Pull Request .

**Comment by AaqibAhamed** [comment]
@xcaptain  please close this issue.

**Comment by xcaptain** [comment]
@AaqibAhamed Yeah, thanks.

**Comment by hsluoyz** [comment]
Will this cause compatibility downgrade? Like .NetCore 2.2 users cannot use the new versions of EFCore-Adapter?

**Comment by xcaptain** [comment]
Nope, this library still target to .NET Standard 2.0, so .net core 2.0 and above application can use this library. https://docs.microsoft.com/en-us/dotnet/standard/net-standard

I tested this version in my .net core 2.2 project, it works.

**Comment by hsluoyz** [comment]
ok
