### ISSUE TITLE
Fix the code coverage badge

### ISSUE THREAD

**Issue by hsluoyz** [casbin-net/EFCore-Adapter#18]
Can anyone help fix the badge? @huazhikui @Sagilio 

![image](https://user-images.githubusercontent.com/3787410/83947017-06e47000-a847-11ea-8dae-53b964794a40.png)

https://coveralls.io/github/casbin-net/EFCore-Adapter?branch=master

![image](https://user-images.githubusercontent.com/3787410/83947025-1499f580-a847-11ea-94f0-16417e6aff51.png)

**Comment by Sagilio** [comment]
I have fixed the badge which at my [fork repository](https://github.com/Sagilio/EFCore-Adapter), it like this:
![image](https://user-images.githubusercontent.com/42855245/83953626-4c6b6200-a874-11ea-941e-4926b9308a43.png)

It need to create a travis environment variable named `COVERALLS_REPO_TOKEN` and it value from the `coveralls`, Could you help me create it? Thank you.

**Comment by hsluoyz** [comment]
@Sagilio I think you can add it now.
