### ISSUE TITLE
nuget package dependency requires sqlsever related package in version 1.2.0

### ISSUE THREAD

**Issue by arthuridea** [casbin-net/EFCore-Adapter#21]
In version 1.2.0,the dependency package "Microsoft.EntityFrameworkCore.Design" is replaced with "Microsoft.EntityFrameworkCore.SqlServer".the latter one only works with Microsoft sqlserver database. Is it possible to rollback to "Microsoft.EntityFrameworkCore.Design" which provide an enough support with design-time feature?

**Comment by hsluoyz** [comment]
@arthuridea can we point out the code or commit that causes this change?

**Comment by Sagilio** [comment]
The version `1.2.1` will only have only the `Microsoft.EntityFrameworkCore` dependency package.

**Comment by arthuridea** [comment]
> @arthuridea can we point out the code or commit that causes this change?

the code works well in project reference way. maybe applied a wrong dependency setting when generating nuget spec? only nuget package has a dependency issue.

**Comment by arthuridea** [comment]
> @arthuridea can we point out the code or commit that causes this change?

i got the point. I reviewed code back to version 1.2.0 which nuget package based on uses a wrong package reference.this is already fixed by @Sagilio in latter version and merged. this issue will be fix when new nuget package publishing.

**Comment by hsluoyz** [comment]
Closed as resloved.
