### ISSUE TITLE
use EFCore-Adapter is fail

### ISSUE THREAD

**Issue by Hareis** [casbin-net/EFCore-Adapter#28]
![image](https://user-images.githubusercontent.com/11290701/98511064-27ee3880-229f-11eb-8a3a-932f49b5d96a.png)
i used 1.4.0
try it to rollback 1.3.1, it's successful
but i found the other problem,

![image](https://user-images.githubusercontent.com/11290701/98512639-96cc9100-22a1-11eb-892e-b7b1be02a3c1.png)

![image](https://user-images.githubusercontent.com/11290701/98512661-a2b85300-22a1-11eb-8caf-d55d6ea5c54c.png)

**Comment by hsluoyz** [comment]
@huazhikui @Sagilio

**Comment by hsluoyz** [comment]
@Sagilio have we implemented `AddPolicies()` in this adapter?

**Comment by Sagilio** [comment]
@hsluoyz  @Hareis  We haven't implemented the batch APIs which added at Casbin.NET v1.4.0 yet and we will add these in the next version. 
For the second error, it looks like an error of the MySQL DB provider, you can add a migration manually to create the `CasbinRule` table.

**Comment by hsluoyz** [comment]
Preceded by: https://github.com/casbin-net/EFCore-Adapter/issues/30
