### ISSUE TITLE
CasbinRule table name - consistency across projects

### ISSUE THREAD

**Issue by msdcanderson** [casbin-net/EFCore-Adapter#29]
I have two projects, one in .Net and a Python project.

Both are going to point to the same DB, and share the same casbin table.

I just noticed that in .net the DB table is 'CasbinRule' and the python one is 'casbin_rule' - so the two projects aren't actually using the same table. 

Is there a good way to set them both to the same table name?

I am using:
for Python, the SQLAlchemy adapter - https://github.com/pycasbin/sqlalchemy-adapter
for .NET, the EFCore adapter - https://github.com/casbin-net/EFCore-Adapter

Thank you

**Comment by hsluoyz** [comment]
@huazhikui @Sagilio

**Comment by Sagilio** [comment]
You can pass an entity configuration to rename it :
```csharp
var context = new CasbinDbContext<int>(options, new CasbinRuleEntityTypeConfiguration());
```
The CasbinRuleEntityTypeConfiguration like this :
```csharp
public class CasbinRuleEntityTypeConfiguration : IEntityTypeConfiguration<CasbinRule<int>>
{
    public void Configure(EntityTypeBuilder<CasbinRule<int>> builder)
    {
        builder.ToTable("casbin_rule");

        // You can also use this to rename the column name.
        builder.Property(rule => rule.Id).HasColumnName("id");
        builder.Property(rule => rule.PType).HasColumnName("ptype");
        builder.Property(rule => rule.V0).HasColumnName("v0");
        builder.Property(rule => rule.V1).HasColumnName("v1");
        builder.Property(rule => rule.V2).HasColumnName("v2");
        builder.Property(rule => rule.V3).HasColumnName("v3");
        builder.Property(rule => rule.V4).HasColumnName("v4");
        builder.Property(rule => rule.V5).HasColumnName("v5");
    }
}
```
If you use a custom DbContext class, you can configure it by overwriting the OnModelCreating method.

**Comment by msdcanderson** [comment]
Great,  thanks @Sagilio

**Comment by hsluoyz** [comment]
Based on our discussion here: https://github.com/casbin-rs/diesel-adapter/pull/58#issuecomment-769847842, we will rename default names to `casbin_rule` and `ptype`.

@Sagilio plz find time to update this adapter (and ideally also other adapters). Make a PR to close this issue. Thanks!

**Comment by hsluoyz** [comment]
@msdcanderson fixed by: https://github.com/casbin-net/EFCore-Adapter/pull/37 . The .NET DB table is renamed to `casbin_rule`.

**Comment by iongion** [comment]
How do you configure the table name in a subclass of  `CasbinDbContext<int>` ?

```
    public class AppCasbinDbContext : CasbinDbContext<int>
    {
        protected readonly IConfiguration _configuration;
        public AppCasbinDbContext(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public AppCasbinDbContext(DbContextOptions<AppCasbinDbContext> options, IConfiguration configuration) : base(options)
        {
            _configuration = configuration;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
             // What ?
        }
    }
```
