### ISSUE TITLE
When we can use Casbin 1.4.0 into EFCore-Adapter? 

### ISSUE THREAD

**Issue by kbsiva** [casbin-net/EFCore-Adapter#31]
When we can use Casbin 1.4.0 into EFCore-Adapter code?
because whenever in NuGet package manager EF Core1.3.0 is the latest version, when will be the latest version comes?

**Comment by hsluoyz** [comment]
@Sagilio

**Comment by Sagilio** [comment]
> When we can use Casbin 1.4.0 into EFCore-Adapter code?
> because whenever in NuGet package manager EF Core1.3.0 is the latest version, when will be the latest version comes?

I am trying to implement the new interface，It will be released in a few days.

**Comment by hsluoyz** [comment]
@Sagilio plz make a new release.

**Comment by Sagilio** [comment]
> @Sagilio plz make a new release.

Already released.

**Comment by hsluoyz** [comment]
@kbsiva see: https://github.com/casbin-net/EFCore-Adapter/releases/tag/v1.3.1

**Comment by kbsiva** [comment]
Thank you. Taken latest..
