### ISSUE TITLE
SQL Adapter it throws error on loadfilter "The data types text and varchar are incompatible in the equal to operator."

### ISSUE THREAD

**Issue by kbsiva** [casbin-net/EFCore-Adapter#35]
Hi Team,
  I am using enforcer.LoadFilterPolicy with filter, it throws error " the data type text and varchar are incompatible".
  I debugged further and the issue is the DB is text field and it takes nVarchar() for comparing and "=" is used. I have corrected the code locally to work and I can give the fix as given below>

```c#
// Error while locading:
enforcer.LoadFilteredPolicy(new Filter
            {
                P = new List<string> { "", "", "","domainname" },
            });
```

Degug Query result:
 
```
((Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<Casbin.NET.Adapter.EFCore.CasbinRule<int>>)query).DebugView.Query
DECLARE @__policyType_0 nvarchar(4000) = N'p';
DECLARE @__field_1 nvarchar(4000) = N'prledit';

DECLARE @__policyType_0 nvarchar(4000) = N'p';
DECLARE @__field_1 nvarchar(4000) = N'prledit';

**SELECT [c].[Id], [c].[PType], [c].[V0], [c].[V1], [c].[V2], [c].[V3], [c].[V4], [c].[V5]
FROM [CasbinRule] AS [c]
WHERE ([c].[PType] = @__policyType_0) AND ([c].[V3] = @__field_1)**
Error:
The data types text and varchar are incompatible in the equal to operator.

Corrected Query:
_**SELECT [c].[Id], [c].[PType], [c].[V0], [c].[V1], [c].[V2], [c].[V3], [c].[V4], [c].[V5]
FROM [CasbinRule] AS [c]
WHERE ((@__policyType_0 LIKE N'') OR (CHARINDEX(@__policyType_0, [c].[PType]) > 0)) AND ((@__field_1 LIKE N'') OR (CHARINDEX(@__field_1, [c].[V3]) > 0))**_
```

Code changes Required:

CasbinRulesExtension.cs file Line No 81.

```
      Error causing line: query = query.Where(p => string.Equals(p.PType, policyType));
        Corrected Code:  query = query.Where(p => p.PType.Contains(policyType));
```

Similarly for other indexes as highlighted here:

```c#
 if (fieldIndex <= 2 && lastIndex > 2)
            {
                string field = fieldValuesList[2 - fieldIndex];
                if (string.IsNullOrWhiteSpace(field) is false)
                {
                    **query = query.Where(p => p.V2.Contains(field));**
                }
            }
```
**Actual error message:**
Microsoft.Data.SqlClient.SqlException: 'The data types text and nvarchar are incompatible in the equal to operator.'

Thanks
siva

**Comment by hsluoyz** [comment]
@Sagilio can you take a look at this issue?

**Comment by kbsiva** [comment]
@hsluoyz I have the fix for it can I change the code?

**Comment by hsluoyz** [comment]
@kbsiva of course! Can you make a PR to fix it?

**Comment by kbsiva** [comment]
@hsluoyz  I have created a pull request please review it once.
This is the first time I am creating a PR. Please verify it once.
Thanks
Siva

**Comment by xcaptain** [comment]
Do you have any special reason to use a text type to store policy? I think nvarchar is enough since each policy won't be too long.

**Comment by kbsiva** [comment]
Hi Team,
So the only solution is to change the type of column to varchar(max) instead of text?
thanks
Siva

**Comment by xcaptain** [comment]
I think so, using `like` may cause performance issue, change to `varchar(max)` should solve your issue.

**Comment by hsluoyz** [comment]
@Sagilio
