### ISSUE TITLE
LoadFilteredPolicy not working when both P and G are defined for Filter

### ISSUE THREAD

**Issue by mrsuau627** [casbin-net/EFCore-Adapter#53]
I'm trying to load a subset of policies similar to the example shown here in the Casbin docs:
https://casbin.org/docs/en/policy-subset-loading

I have an RBAC model with domains and I want to do exactly what is shown in this example where I can load a filtered policy with everything from "domain1". I have 1 "g" group/role defined for "domain1" and then I've given that group permission to 2 objects also in "domain1"...so my casbin_rule table has 3 rows: 1 "g" row and 2 "p" rows. 

After I was having issues, I stepped through the LoadFilteredPolicy code, and determined that

- If I set it with only the P filter, it loads the 2 rows from casbin_rule
- if I set it with only the G filter, it loads the 1 row from casbin_rule
- if I set up a filter with both "P" and "G" set to values, the function loads with 0 rows. 

The reason is because in CasbinRuleExtension.ApplyQueryFilter, it performs the following code
```
            if (filter.P is not null)
            {
                query = query.ApplyQueryFilter(PermConstants.DefaultPolicyType, 0, filter.P);
            }

            if (filter.G is not null)
            {
                query = query.ApplyQueryFilter(PermConstants.DefaultGroupingPolicyType, 0, filter.G);
            }
```
This results in a query that takes the the P filter **AND** the G filter. This will never return any values. In order for both to work, there would have to be an **OR** instead of **AND**.

As I mentioned above, based on the example here: https://casbin.org/docs/en/policy-subset-loading, it seems like this should work as I've described where it does an OR between the 2 filters. Is this a bug? Is there a workaround you can provide?

Thanks!

**Comment by hsluoyz** [comment]
@MRGUOKING should be labeled as bug

**Comment by sagilio** [comment]
@mrsuau627 I think you are right, it looks like a bug, I will fix it later.
You can combine the results of calling with filters of P and G to obtain the correct results temporarily.

**Comment by mrsuau627** [comment]
@sagilio Can you provide an example of how to do this? Thanks!

**Comment by sagilio** [comment]
@mrsuau627 I am sorry to reply too late, would you like to review the PR #54 for this issue?

**Comment by mrsuau627** [comment]
> @mrsuau627 I am sorry to reply too late, would you like to review the PR #54 for this issue?

@sagilio  I will take a look this weekend. Thank you!
