### ISSUE TITLE
EFCore adapter performance and caching [Question]

### ISSUE THREAD

**Issue by tigertop** [casbin-net/efcore-adapter#55]
Hi,

I apologize if my question may sounds simple or if I have overlooked something, or if this is the wrong place to ask this question. We are using Casbin.Net for performing authorization library for our microservice project. We also use MassTransit and we need to perform authorization of commands. For that we are implemented custom filters where we make calls to the authorization service.
If we are regsitering the services as shown in the readme of this repo then a single DBContext and the enforcers are singleton for each request. In this scenario basically DBContext becomes singleton and after first query all policies from DB are loaded and cached in-memory. The first problem that we are facing is that in this scenario production use (100+ users) a lot of concurrent updates happen and we are getting EF errors saying that the DBContext cannot be used by different threads, which totally logical. If we change the service registration and a new DContext is constructed for each request we are hitting performance issues as each time it has to read all policies from the database. 
To be honest I didn't find a proper place to hook in the caching in the EFCore adaptor, and that only leaves us with options to hook into EF Core's in-memeory "shared cache" or cache the command results at MassTransit level. Am I missing something? What production level best-practices are there for Casbin.net and EFCore Adapter in-terms of performance? 

Thanks for your patience!

**Comment by sagilio** [comment]
I am working to solve it in the new version. 
All policies have cached in the `Model` instance in the `Enforcer`, but the model is not a synchronized store, and we can not make the model and enforcer completely isolated.

I plan to do the following in the new version to improve this situation:
1. Provide `SyncModel`. it allows management policy synchronized.
2. Add a new option `lazyLoadPolicy` at the `Enofrcer`, it allows do not load of all policy when creating a new enforcer instance.
3. Isolate the cache from the enforcer instance, including `EnforceCache` `ExpresstionCache` `GFunctionCache`.

I think the best practice is to use singleton SyncModel/EnforceCache instance/instance pool and open the `AutoSave` option on the Adapter, and use the lazyLoadPolicy option to create a new Enforcer instance. here is a sample: https://github.com/casbin-net/casbin-aspnetcore/blob/master/src/Casbin.AspNetCore.Core/DefaultEnforcerProvider.cs.

**Comment by hsluoyz** [comment]
@tigertop EFCore adapter has implemented the filtered adapter inteface: https://github.com/casbin-net/efcore-adapter/search?q=filtered&type=code , so you can use `LoadFilteredPolicy()` to do sharding, see details at: https://casbin.org/docs/performance
