### ISSUE TITLE
DeleteRoleForUser is not working

### ISSUE THREAD

**Issue by alexssandro** [casbin-net/efcore-adapter#58]
Hi, I am using EFAdapter with cosmos DB, and seems the method  DeleteRoleForUser is not working.
I am using SavePolicy after calling DeleteRoleForUser(user, role, domain);

is there something I can do?

**Comment by sagilio** [comment]
@alexssandro Could you provide a code example to help us reproduce this issue case？

**Comment by hsluoyz** [comment]
@alexssandro the `DeleteRoleForUser()` API requires the 1st arg of your policy is user and 2nd arg is role. Can you try using EFAdapter with another DB like MySQL? So we can know if it's the DB issue.

```csharp
public static bool DeleteRoleForUser(this IEnforcer enforcer, string user, string role, string domain = null)
        {
            return domain is null
                ? enforcer.RemoveGroupingPolicy(user, role)
                : enforcer.RemoveGroupingPolicy(user, role, domain);
        }
```

https://github.com/casbin/Casbin.NET/blob/abedaaceb0dab5c2245a1890a5bd1c544d6c3973/Casbin/Extensions/Enforcer/RbacEnforcerExtension.cs#L183-L188

**Comment by hsluoyz** [comment]
Closed for now given this issue is too old. Feel free to ping it back
