### ISSUE TITLE
Casbin.Adapter.EFCore Results in Duplicate Policy Records in PostgreSQL Database

### ISSUE THREAD

**Issue by Jimmy3139** [casbin-net/efcore-adapter#65]
Issue Description:

When using the EFCore adapter (Casbin.Adapter.EFCore) with Casbin.NET and PostgreSQL as the database, I noticed that after calling AddPolicy() and SavePolicy(), duplicate policy records are present in the database. I am certain that I am not calling AddPolicy() multiple times in my code.

Steps to Reproduce:

Configure Casbin.NET to use the Casbin.Adapter.EFCore adapter and connect to a PostgreSQL database.
Call AddPolicy() in the code to add a new policy.
Call SavePolicy() to save the changes.
Check the database and observe duplicate policy records.
Expected Behavior:

There should be only one new policy record in the database.

Actual Behavior:

There are two identical policy records in the database.

Environment Information:

Operating System: [e.g., MacOS]
.NET Version: [e.g., .NET 6.0]
Casbin.NET Version: [e.g., 1.14.0 ]
Casbin.NET.Adapter.EFCore Version: [e.g., 1.8.1]
Casbin.AspNetCore.Core Version : [e.g., 0.2.1]
PostgreSQL Version: [e.g., 14.4]
Any other libraries or frameworks that might be relevant

#### Here is how I register the service
Code Sample:
```C#
public static class CasbinConfigurationExtensions
{
    public static IServiceCollection AddCustomCasbinConfiguration(this IServiceCollection services, IConfiguration configuration)
    {
        var options = new DbContextOptionsBuilder<CasbinDbContext<long>>()
            .UseNpgsql(configuration.GetConnectionString("DefaultConnection"))
            .Options;
        var context = new CasbinDbContext<long>(options, defaultSchemaName: "manage");
        context.Database.EnsureCreated();
        services.AddSingleton<Enforcer>(provider =>
        {
            var efCoreAdapter = new EFCoreAdapter<long>(context);
            var e = new Enforcer("./CasbinConfigs/basic_model.conf", efCoreAdapter);
            e.LoadPolicy();
            return e;
        });

        return services;
    }
}

```
----

#### Program.cs

```C#

builder.Services.AddCustomCasbinConfiguration(configuration);

```
----
#### DI

```C#
 public class XXXService : IXXXService
{
    private readonly Enforcer _enforcer;
    public XXXService( Enforcer enforcer)
    {
  
        _enforcer = enforcer;
    }
}

```
#### main

```C#
 _enforcer.AddPolicy(roleId, path, method);
  _enforcer.SavePolicy();

```

**Comment by sagilio** [comment]
The policy will be added to DB when calling `AddPolicy` at the default options, and need not call the `SavePolicy`.

If you would like to save the policy manually, you can this API to disable the autosave.
```
enforcer.EnableAutoSave(false);
```

**Comment by Jimmy3139** [comment]
@sagilio 
Thank you for your answer, the problem is solved.

**Comment by VictorioBerra** [comment]
Found this looking for DI approach to getting IEnforcer, thanks for your sample @Jimmy3139 

I ended up using this:

```csharp
    builder.Services.AddScoped(provider =>
    {
        var enforcerProvider = provider.GetRequiredService<IEnforcerProvider>();
        return enforcerProvider.GetEnforcer()!;
    });
```

I noticed `IEnforcerProvider` was registered for my use.
