### ISSUE TITLE
Release of v2

### ISSUE THREAD

**Issue by homorozeanu** [casbin-net/efcore-adapter#66]
Hi efcore-adapter Team,

we would like to build our AuthZ custom solution based on Casbin.NET version 2. As we use the EFCoreAdapter to store/load the policies we are wondering if you could share with use the release date of the EFCoreAdapter v2.0.0. Is there any roadmap or additional information about the release date?

Best regards
George

**Comment by sagilio** [comment]
Hi, we are actively preparing for the v2 release. It will be released this week.

**Comment by hsluoyz** [comment]
@homorozeanu v2 already released, please try it: https://github.com/casbin-net/efcore-adapter/releases/tag/v2.0.0
