### ISSUE TITLE
Throw EntryPointNotFoundException on .Net8 project

### ISSUE THREAD

**Issue by crskycode** [casbin-net/efcore-adapter#73]
I'm trying to add this adapter to my .Net8 WebAPI project, but when I call `AddPolicy`, I get an `EntryPointNotFoundException` at [this](https://github.com/casbin-net/efcore-adapter/blob/19ab103bddbb0d6e4c8b51e19a75a9c6826be582/Casbin.Persist.Adapter.EFCore/EFCoreAdapter.cs#L116C7-L116C35) location.

I tried compiling the adapter on my machine, removing the `preview` at  [this](https://github.com/casbin-net/efcore-adapter/blob/19ab103bddbb0d6e4c8b51e19a75a9c6826be582/Casbin.Persist.Adapter.EFCore/Casbin.Persist.Adapter.EFCore.csproj#L24) line, and it works.

**Comment by hsluoyz** [comment]
@crskycode can you make a PR to fix it?

**Comment by jveko** [comment]
Why i still got the Throw EntryPointNotFoundException? is there any problem? i try to build by myself and install locally and it works, but when i do reference to nuget.org got error
